### ISSUE TITLE
CODE 64 ISSUE

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#14]
Please note that the CODE 64 issue has not yet been resolved.  User can not submit new CODES as a result.  Clicking "SAVE" results in a yellow screen code 64.  Your prompt attention to this matter would be greatly appreciated!
![image](https://user-images.githubusercontent.com/61298381/74990263-b52eeb80-53f7-11ea-95ad-5969aca87bbe.png)

**Comment by mason-anderson** [comment]
submitting codes is fixed in commit 21c8890.
