### ISSUE TITLE
list of current little issues (josh)

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#15]
1. can we please have the "raise an issue" directly under the help menu button (rather than digging through several menus to get to it?
2. the cross-check reports for SERVICE, FINE ARTS, ATHLETICS, and HONOUR ROLLS require the current year TOTAL and the cumulative YEARS total columns (please).

**Comment by Joshua-Chiu** [comment]
Fixed Part 1 of the issue in  620414e.

**Comment by Joshua-Chiu** [comment]
Fixed Part 2 of the issue in commit efd46d7.
