### ISSUE TITLE
DECIMALS ON GRAD REPORTS

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#18]
All the grad reports have points indicated at three decimal places which causes a lot of width when printing the reports.  Evin Li for example.  So, to help shrink this, let's make ALL POINTS display at only one decimal place.  This includes all the reports under the GRAD REPORTS button.  Merci!

**Comment by Joshua-Chiu** [comment]
Decimals removed in commit 5d475f3.
