### ISSUE TITLE
SYSTEM-WIDE BUG

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#20]
Dear Developers,
Apparently, there is a system-wide bug with the NULLIFICATION feature.  After nullifying and refreshing, a student retains their original status.  In other words, the nullification does not work and bottom line, it's broken. :)   PETH

**Comment by mason-anderson** [comment]
This bug fails to replicate

**Comment by npetheriot** [comment]
Correct -- after doing a refresh, it apparently does not retain the nullification.  I didn't think of doing a refresh to check.
