### ISSUE TITLE
SCHOLARSHIP history not revealed

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#21]
Please find a way to have scholarship uploads appear on the RECENT ACTIONS BOX.  This way I can know what Ms Chan is up to...and what she's uploading or doing.  PETH :)

**Comment by npetheriot** [comment]
We haven't forgotten about this?

**Comment by mason-anderson** [comment]
all changes to scholarship averages through uploads and direct entry are now logged but only if they are changed to a different value
