### ISSUE TITLE
PLIST CUT OFF FIX:  AFTER NEW INSTALL

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#22]
Hi Josh / Mason,
So, as you are aware, the database is now running externally.  We uploaded the student data just last night.  At first, I was horrified that the PLIST cut offs did not merge over.  But, after a few minutes, voila, it happened.  They were there and they are correct.  There is only only small error.  If you look at the PLIST cut-off screen for the 2016-2017 year, you will notice that there is a 95.000% in TERM 1 for grades 11 and 12.  There actually shouldn't be anything there.  Or there should be the impossible 99.999% showing there.  I figure that there is a minor programming error in that spot.  Can that be fixed?  It should read 99.999% not 95.000%.  MERCI!!!!!!!!!!!!!!!!!!  M PETH  I tried cut/paste the screen shot here but I don't think it worked:
![image](https://user-images.githubusercontent.com/61298381/79919845-00f41600-83e4-11ea-8b5a-d9f6734dcc0c.png)

**Comment by Joshua-Chiu** [comment]
Issue can not be replicated
