### ISSUE TITLE
IMPORT NEW GRADE 8's

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#26]
There is no instruction on the import 'new grade 8s' page regarding the format of the excel document needed.  Should it be CSV?  Should the fields be in a certain order?  What fields what order?  Or is there a sample EXCEL that can be downloaded there at that spot?  That way, the user can maybe paste the new data into the properly formatted document?  Your thoughts?  Peth

**Comment by Joshua-Chiu** [comment]
enhancement completed in commit 55170cc
