### ISSUE TITLE
YELLOW SCREEN WITH DUPLICATE ENTRIES!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#27]
I'm starting the bulk upload of service points now.  I've encountered issues and have stopped.  It seems that it doubles everyone's entries and ends on a yellow screen of death.  When I refresh the entries have been made but they are DOUBLE duplicated!!!  Here is the yellow screen:
![image](https://user-images.githubusercontent.com/61298381/80133705-767df480-8552-11ea-9bf6-46b7b9030430.png)

**Comment by Joshua-Chiu** [comment]
problem fixed in commit 793da61.
