### ISSUE TITLE
BACK-END PROBLEM!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#28]
Bonjour Mason,
So, a little issue has come up.  I'd like you to take a close look at Josh's awards profile and Chris Lu's as well (for example).  database.joshuachiu.com  You will notice, if you look carefully, that Josh and Chris have been allocated points in athletics and fine arts (in the headings and totals).  However, NO athletics or fine arts were ever allocated to them.  Chris has 10 points in FINE ARTS that can't be explain.  And Josh too.  What can be done to rectify this???  Peth  See below:
![image](https://user-images.githubusercontent.com/61298381/80636574-901bb200-8a12-11ea-90bf-90fffd0d5d99.png)

**Comment by Joshua-Chiu** [comment]
patched in commit  320bee8
