### ISSUE TITLE
NEW REVERSE SEARCH FEATURE

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#29]
I would like to humbly and respectfully request a feature that will be of signifcant need and use moving forward.  I call it the "REVERSE SEARCH" feature.  These feature would be a new button under the REPORTS menu.  Basically, it would allow the user to display or to download/print a report accessed by service, athletic, or fine arts code.  For example, the school service club is CODE 1.  If the user wants to pull a report of all students in the service club for the current year, they could access the REVERSE SEARCH feature.  I imagine it being accessed by the same CODES MENU that we already have existing.  Maybe a drop down menu?  What would the report include?
1. name of group
2. first& last names of participants
3. student number
4. grade
5 number of points allocated
The report would not be by grade.  Instead, it would pull the list from the entire current school year (by default).  However, the report selections menu should have the option of selecting the YEAR for the report as well.  So, if the user would like to pull a list of last year's service club, it would be possible.
If you require further details or have questions, please advise/contact!  Peth

**Comment by mason-anderson** [comment]
There is not yet page for reverse search but right now it is possible to filter students by putting `has_point:SE01` in a search.

**Comment by npetheriot** [comment]
I understand.  However, I tried it and I can not get it to work.  What am I doing wrong?  I type has_point:AT08 in the searchbar and it gives me a random list of students that did not do service.  SE01 is service club.  So, it should show me all students that were in service club?  Correct?

**Comment by Joshua-Chiu** [comment]
`has_point:SE08`, not `has_point:AT08`, shows a list of ALL students who were (at any point in time) on SE08. You can further filter with `has_point:SE08 grade:08`.

**Comment by npetheriot** [comment]
UNDER THE REPORTS MENU, create new button for reverse search called "SEARCH BY ACTIVITY"

**Comment by Joshua-Chiu** [comment]
Just a reminder that under the grade selection drop-down menu, we will need one selection for "whole school" or "grade 8-12". This way, we can get one report of all kids in the school in one particular group. MERCI!

**Comment by Joshua-Chiu** [comment]
it works as of 484563a
