### ISSUE TITLE
USER LEVEL ACCESS

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#30]
OK, I've just discovered another need.  The athletic department will be having limited access to the database (not SUPERUSER).  They will primarily have access to the DIRECT ENTRY tab.  However, I have just found out that they will also need access to the REPORTS tab as well.  They will be pulling reports for athletic purposes and big block status etc...  HOWEVER, that being said, I would not want them to have access to the scholarship, service, and fine arts reports.  They shouldn't be able to pull reports that are not related to ATHLETICS.  So, can we add the REPORTS level access to the USERS?  Also, within that, can we choose what reports they are able to access?  PETH

**Comment by Joshua-Chiu** [comment]
For the athletic reports access levels, we need the following. I've tried to used layered flowcharts to make it easier to understand:

REPORTS
-Annual
-Annual Certificates (athletic only)
-Athletic Awards (access to all)

REPORTS
-Crosscheck
-Athletic points (only)

REPORTS
-Annual Trophies
-Trophy Type (athletic only)

REPORTS
-Graduation
-Grad Awards (athletic candidates only)

It is basically access to all the athletic-type of reports that we have on our system. Peth

**Comment by npetheriot** [comment]
Thank you for adding that!

**Comment by Joshua-Chiu** [comment]
Completed exactly 1 year later in 90c8f7d
