### ISSUE TITLE
simple time-out request

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#36]
Bonjour!  Can you please set my 'time-out' timer to 20 minutes.  It is currently way too short and I keep getting logged out and I need to resign-in again and again.  20 minutes should be good.  Peth

**Comment by Joshua-Chiu** [comment]
SESSION_SECURITY_WARN_AFTER to 1140 seconds
SESSION_SECURITY_EXPIRE_AFTER to 1200 seconds
Fixed in  5165126
