### ISSUE TITLE
minor report adjustment

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#37]
Under the REPORTS TAB....then ANNUAL TROPHIES....then SCHOLARSHIP CANDIDATES...

This scholarship candidates report requires the two-term average to be printed on the report.  Right now, it only lists, term one and term two separately.  We need to add "two term average".

Sorry about this.  I'm sure we discussed it originally when the report was set up but I'm only noticing it now that I require the reports to be printed for actual use!  Thanks!  Peth

**Comment by Joshua-Chiu** [comment]
Fixed problem in 9959f2b
Caveat - Potential Issue: Please check the order of the generated SCHOLARSHIP CANDIDATES lists.

**Comment by npetheriot** [comment]
@Joshua-Chiu Perfect, just what I needed!  However, everything is scrunched and difficult to read like one long sentence.  Look:

**Comment by Joshua-Chiu** [comment]
Added space in commit 9054943 , no vertical bars added

**Comment by npetheriot** [comment]
Thanks for the fix
