### ISSUE TITLE
export to excel not working!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#39]
This morning I needed to pull some reports for the committee.  Since some members prefer it in excel, I was trying to print the honour roll certificates recipients list in excel.  The excel button is not working.  When you click it, nothing happens!  I'm talking about this menu:
![image](https://user-images.githubusercontent.com/61298381/81189833-e8e7cf00-8f6b-11ea-9235-dee361791294.png)

**Comment by npetheriot** [comment]
BY THE WAY, it might just be the PLIST EXCEL sheets that don't work!!!

**Comment by Joshua-Chiu** [comment]
Principal's List apostrophe problem. Patched by bodge in removing single quote. Fixed in commit 92eb8c7
