### ISSUE TITLE
graduation report scholarship

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#41]
Pull the graduation report for scholarship.  Look at Catherine Wu's overall percentage.  Now look where she is in the list.  Do we know why the dbase has her out of order?  So mysterious!  Please advise!

**Comment by mason-anderson** [comment]
This behavior is expected. The grad report for scholarship ranks by scholar points which aren't handed out linearly based on average, so one student could have more scholar points than another even with a slightly lower average. For example 100% in t1 and 90% in t2 is worth more scholar points than 95% in both terms.
