### ISSUE TITLE
3+ sport athletes

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#42]
Under the REPORTS menu...looking at the ATHLETIC reports...where there are 3-sport, 4-sport,, 5- sports athletes.  One of those reports is supposed to be a "3+ sport athletes".  It is a list of all the students who have three or more sports within in the current year.  You will notice that there are two 3-sport athletes reports currently there.  The second one is supposed to be a "3+ sport".  Can this please be fixed?

**Comment by Joshua-Chiu** [comment]
Front end fixed, @mason-anderson complete complete backend logic and integration

**Comment by Joshua-Chiu** [comment]
-exactly 3
-3 or more
-exactly 4
-4 or more

**Comment by Joshua-Chiu** [comment]
Operational in e146189
