### ISSUE TITLE
honour roll upload moving forward (future)

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#44]
OK, this is just fresh in.  Since grade 8's and 9's will no longer have marks on their report cards, we won't be able to do honour roll with them.  This causes a problem.  A solution will be to wait until the end of the year, June, to get the final report card mark (which is a percentage) and assign it to BOTH terms for the grade 8's and 9's.  Then, instead of having awards ceremonies for the grade 8s and 9s in June, have them in September instead.  So, here's my question (for the future).  If we do not receive the excel spreadsheets on time to be able to upload them in June, can we upload them in September for the previous year.  I am concerned about the grade 'roll-over' that happens.  Can we make it so that we can retroactively (if need be) upload the grade 8 and 9 report cards for the previous year?  We may just need to do this in the future.  Need to make sure this ability is in the system.  Peth

**Comment by Joshua-Chiu** [comment]
feature not supported, too error prone.
