### ISSUE TITLE
PRINCIPAL'S LIST EXCEL DOES NOT WORK

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#45]
Mr. Lai has been on today pulling some required reports.  He is reporting that the Principal's List report in EXCEL format does not work.  I do believe I've previously mentioned this one to Josh.  I thought maybe it was already fixed.  ANYWAY, he requires excel format.  Is it an easy fix?  Merci!!!!

**Comment by Joshua-Chiu** [comment]
Can not replicate issue. Please explain.

**Comment by npetheriot** [comment]
Hey, nice to have tech support back.  What invalid??  How dare you!!!  Not invalid.  Very valid.  You can print an excel report for PRINCIPAL's list certificates.  The system does nothing when you click on the EXCEL button.  All the other certificates work except that one.  Make sense mon ami?

**Comment by npetheriot** [comment]
Issue was solved by Josh!  All working well now!
