### ISSUE TITLE
SYSTEM TIMEOUT ON STUDENT DELETION

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#47]
OK, so, now that we're back to using the database from the school server, I wanted to upload the students with the most recent data.  I went to DELETE the old students (approx 1200) before installing new students.  In doing this, the system was only able to delete about 200 students before timing out.  The same thing happened multiple times.  How to resolve?

**Comment by Joshua-Chiu** [comment]
Fixed in latest revision. Update.
