### ISSUE TITLE
ADMINISTRATION STUDENT VIEW SCREEN

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#53]
Hikari and Veronika came for the first time today to check the student database and so far so good!!!!  Everything seems to be working as they're manually making changes to student data and adding in the odd new student.  They had quite a bit of difficulty reading horizontally off the STUDENT list view screen.  They (and I) are wondering if it is possible to separate each student with a horizontal bar?  Or, alternatively, to highlight the students in alternating colours to make it easy to follow across horizontally.  There was a lot of misread going on with them today as their eyes were skipping lines as they were reading across.  Any easy fix for this?

**Comment by Joshua-Chiu** [comment]
Feature already exists
