### ISSUE TITLE
HOMEROOMS ARE ALL ZERO??????????????

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#54]
OH goodness!  The homerooms are all zero when printing reports for certificates, pins, etc.  Could this have something to do with the fact that you separated grade and homeroom back in the admin student files?  See image:
![image](https://user-images.githubusercontent.com/61298381/101225269-ddfe3580-3645-11eb-898e-39d767191744.png)

**Comment by Joshua-Chiu** [comment]
closing with 1a92c5b
