### ISSUE TITLE
export function producing yellow screen

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#56]
![image](https://user-images.githubusercontent.com/61298381/101536907-80bcf980-394f-11eb-999b-358de5cc9333.png)
![image](https://user-images.githubusercontent.com/61298381/101536941-8dd9e880-394f-11eb-85ba-09a3a0d91915.png)

**Comment by npetheriot** [comment]
I really need this EXPORT function to work.  For example, I'd like to print an exported list of all the grade 8s into an excel sheet.  Why does the EXPORT button produce a YELLOW SCREEN????  Peth 💯

**Comment by Joshua-Chiu** [comment]
Use the print annual certificate function and pull a certificate like so
![image](https://user-images.githubusercontent.com/32609753/116216391-6d8fa800-a6fd-11eb-92d6-4c8c96c75b26.png)

Will close issue in one week
