### ISSUE TITLE
DISPLAY 300 instead of 100?

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#57]
Can we change the STUDENT screen under admin to display a minimum of 300 students at at time?  I'd like to be able to select and export to CSV without having to cut and paste several excell sheets together to accomplish this.  So this below (to display 300):
![image](https://user-images.githubusercontent.com/61298381/101672497-c8548b80-3a0a-11eb-950f-1b37847b49ea.png)

**Comment by Joshua-Chiu** [comment]
Fixed in cb5b86c
