### ISSUE TITLE
EXCEL FILE FOR GRADE 8/9 HONOUR ROLL BASE POINTS

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#67]
Hello Friendly Tech Team -- due to the fact that the grade 8 and 9's no longer get report cards with percentages, we have to give all students 80% average in order to give base honour roll points.  This will keep them in sync with achieving silver/gold pins and other awards.  Without honour roll points in grade 8 and 9, most will not be able to ever achieve a gold pin status...it will be too far out of reach.  So, to do this, I need to do a bulk upload of the T1 and T2 marks.  I need an excel report that can download the ACTIVE students in the individual grade levels.  So, the report would need student number, last name, t1 and t2 columns (basically the bulk upload report for honour roll with the student names and numbers filled in already).  I managed to makeshift the data entry for this year.  It wasn't easy though as I had to "Cut and Paste" from the grade list...then I had to remove all the "#" students from the list manually.  We don't want the "#" inactive students getting honour roll credit if they're not currently attending the school.  If you require further information regarding this report, please ask!  MERCI MONSIEUR PETH! :)

**Comment by Joshua-Chiu** [comment]
For the database calculator, it is easier to generate a csv for you to upload as the excel file that is received from Ms Chan changes too often. 

As for the specified report, you can go to the direct entry for scholar direct entry and download the prefilled csv after you update the database to V2

**Comment by Joshua-Chiu** [comment]
Created feature in 653d988
