### ISSUE TITLE
ENSURE ROLL-OVER without error

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#71]
If you recall, we had "fantôme" students and random electronic particles affect the "roll over" in September.  Is there something that you said you would do to ensure that this does not happen again.  If you recall, it caused glitches in pulling reports and many yellow screens of death. PETH

**Comment by Joshua-Chiu** [comment]
Click the Settings in the navbar (the actual button, not the dropdowns). Click Database Integrity Check. Pull the integrity report. Will close issue in one week.
