### ISSUE TITLE
excessive decimal place!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#72]
![image](https://user-images.githubusercontent.com/61298381/118161989-16fcbc00-b3d5-11eb-9019-01603df68d49.png)

**Comment by Joshua-Chiu** [comment]
![image](https://user-images.githubusercontent.com/32609753/119132299-65224880-b9ef-11eb-87c8-9f9a7ed3b311.png)
Issue not replicable. Likely fixed in update.
