### ISSUE TITLE
PRINTING REPORTS ADDITION

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#73]
OK, so this is the most recent option that needs to be added to ALL report printing options.  We need to add a fifth grade choice.  Aside from individually printing grade 8,9,10,11,12 for reports, we need a grade 8-12 option to be able to print whole school reports in one as well.  This is a recent development and request.  Let me know if you have any questions.

**Comment by Joshua-Chiu** [comment]
Students in report generation require a grade and start year to process the request. This feature requires a redesign of the queryParse feature which is the foundation the reports modules. In short, while there may be a caveat that may allow this feature, it probably won't happen.

**Comment by Joshua-Chiu** [comment]
obtained permission to not fix
