### ISSUE TITLE
SIGNTURE BOX PROBLEM URGENT!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#76]
I'm having a problem with the signature box not working.  This is urgent because certificates need to be printed next week.  I've tried uploading the white.png file at the 500X250 size suggested.  I get yellow screen.  Without inserting a white box, the certificate look like this:
![image](https://user-images.githubusercontent.com/61298381/119181769-e9dc8900-ba26-11eb-931e-abfbea968f3f.png)

**Comment by npetheriot** [comment]
![image](https://user-images.githubusercontent.com/61298381/119202669-22d82600-ba46-11eb-9a50-6993492f0f09.png)

**Comment by Joshua-Chiu** [comment]
chmod 775 the upload dir
