### ISSUE TITLE
CERTIFICATE SIGNATURE BOX REMOVAL

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#80]
As you know, the signature box appears on the printed certificates.  I would like the signature feature to be permanently removed if possible.  It has been nothing but problems since it's inception.

**Comment by npetheriot** [comment]
Principal's can just sign their own certificates or use the rubber stamp which the office has.

**Comment by Joshua-Chiu** [comment]
done in 37b5624
