### ISSUE TITLE
SHOW TOP 40 INSTEAD OF 30?

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#82]
Can you adjust the top scholars list under graduation reports to show the top 40 instead of top 30?  This one:
![image](https://user-images.githubusercontent.com/61298381/119905820-c8d1d780-bf01-11eb-90d8-b8842db1f7dc.png)

**Comment by Joshua-Chiu** [comment]
fixed in 37b5624
