### ISSUE TITLE
REVERSE SEARCH IS BROKEN!

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#83]
Josh - I guess we missed this last week when you were here?  It was working before you did the update...but now???  The CLUBS search or REVERSE search, as I call it, is broken.  See below the yellow screen:
![image](https://user-images.githubusercontent.com/61298381/120856296-7c574f00-c534-11eb-96e2-08e774f2468a.png)

**Comment by Joshua-Chiu** [comment]
fixed in 0a1dc16
